### PR TITLE
fix for symfony3

### PR DESCRIPTION
**Pull request by hjanuschka**
fixes fatal error when using symfony3

### CODE REVIEW

**Comment by JulienDemangeon** [comment]
This fix is already merged from your precedent commit 8497e7042d3a15d473afe7713c33f3e3868dabac
You can use it from the v0.3 tag ;)

**Comment by hjanuschka** [comment]
that pr is about another file! 

Von meinem iPhone gesendet

**Comment by JulienDemangeon** [comment]
Oups, sorry for the mistake !

**Comment by hjanuschka** [comment]
so you merge it?

**Comment by JulienDemangeon** [comment]
You can find it in the v0.3.1 release ;)

**Pull request merged**
